model:
  msdf_out_ch: 120
  lfmwb_mid_ch: 192
  use_cross_gate: true
  use_mask_guide: false
  ssm_d_state: 1
  ssm_ratio: 2.0
  ssm_rank_ratio: 2.0
  ssm_dt_rank: auto
  ssm_act_layer: silu
  ssm_conv: 3
  ssm_conv_bias: false
  ssm_drop_rate: 0.0
  ssm_init: v0
  forward_type: v3noz
  mlp_ratio: 2.0
  mlp_act_layer: gelu
  mlp_drop_rate: 0.0
  drop_path_rate: 0.2
  norm_layer: ln
  gmlp: false
  use_checkpoint: false
